# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sort.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sort.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsort.proto\"\x14\n\x05\x41rray\x12\x0b\n\x03\x61rr\x18\x01 \x03(\x05\"\x15\n\x06Result\x12\x0b\n\x03\x61rr\x18\x01 \x03(\x05\x32&\n\x0bSortService\x12\x17\n\x04Sort\x12\x06.Array\x1a\x07.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sort_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARRAY']._serialized_start=14
  _globals['_ARRAY']._serialized_end=34
  _globals['_RESULT']._serialized_start=36
  _globals['_RESULT']._serialized_end=57
  _globals['_SORTSERVICE']._serialized_start=59
  _globals['_SORTSERVICE']._serialized_end=97
# @@protoc_insertion_point(module_scope)
